#!/bin/zsh
# Function to create and track a new git branch


function gnb() {
branch_prefix=''
  while getopts 'f:r:h:' flag; do
    case "${flag}" in
      f) branch_prefix='feature/' ;;
      r) branch_prefix='release/'  ;;
      h) branch_prefix='hotfix/' ;;
      *) branch_prefix='' 
        break;;
    esac
  done
  if [ ! -z "${OPTARG}" ]; then
    branch_name="${OPTARG}"
  else 
    branch_name=$1
  fi
  branch_name="${branch_prefix}${branch_name}"
  print "$branch_name"
  git checkout -b $branch_name && git add remote-origin origin $branch_name
}
